### ISSUE TITLE
not working in iterm 2.1.4

### ISSUE THREAD

**Issue by patrickdo** [sindresorhus/iterm2-snazzy#1]
I'm trying to import the itermcolors files and while they do show up in the Colors-Presets list of iTerm 2.1.4, selecting the Snazzy theme doesn't actually change the colors displayed and doesn't actually work after closing the Preferences window. I have been able to install all other itermcolors files that I've tried, including Cobalt2, Tomorrow Night 80s etc.

**Comment by sindresorhus** [comment]
Upgrade to the latest iTerm2 version.
