### ISSUE TITLE
Import failed in iTerm 

### ISSUE THREAD

**Issue by mattbanks** [sindresorhus/iterm2-snazzy#2]
Downloaded `Snazzy.itermcolors` today and got an error when I opened the file in iTerm:

`The selected file could not be read or did not contain a valid color scheme.`

<img width="532" alt="screenshot 2017-05-15 09 50 42" src="https://cloud.githubusercontent.com/assets/302970/26060774/1257ba2e-3954-11e7-9236-676b38c95e88.png">

macOS Sierra 10.12.4
iTerm2 Build 3.0.15

**Comment by mattbanks** [comment]
nevermind, figured it out :(

**Comment by alexpareto** [comment]
@mattbanks How'd you figure it out?

**Comment by mattbanks** [comment]
@alexpareto right clicking and downloading the file from the github page saved an entire HTML page of it for me. I had to go into the Raw output file and save that, which worked better.

I might do a PR to the readme to link to the raw output to download that. @sindresorhus

**Comment by mattbanks** [comment]
doh, the readme does link to the raw file! I was right clicking on the file in the file list instead of the link in the readme

**Comment by hongyun0** [comment]
Thanks!
