### ISSUE TITLE
Double CWD when used with Pure

### ISSUE THREAD

**Issue by ktalebian** [sindresorhus/iterm2-snazzy#3]
When you use this theme with pure, you get double the CWD. Any ideas why and how to fix this?

<img width="1440" alt="double" src="https://user-images.githubusercontent.com/2308915/38852204-bc72b3e2-41cd-11e8-9a42-6237f476c177.png">

**Comment by sindresorhus** [comment]
This is just a color theme. It has nothing to do with your problem. Try doing some Googling.
