### ISSUE TITLE
Import failed on iTerm2 Build 3.3.9

### ISSUE THREAD

**Issue by Siddharth11** [sindresorhus/iterm2-snazzy#5]
First of all, thanks a lot for making this beautiful theme. 
I've been using for almost ~3 years now! 😄

I was recently setting up new my new Macbook, and tried installing this theme again. I'm getting this error during import 

<img width="425" alt="Screenshot 2020-05-14 at 3 25 01 PM" src="https://user-images.githubusercontent.com/5427715/81939904-3c56be80-95f7-11ea-907a-8940595b92a7.png">

**Comment by sindresorhus** [comment]
I tried re-exporting Snazzy from the latest iTerm version. If that still doesn't work, there's not much I can do.

**Comment by jftheroux-devolutions** [comment]
I first saved the file as, as per the documentation and it wouldn't import. I then cloned the repository and was able to import the config.

That might help someone else in the future.

**Comment by handreistoicescu** [comment]
The one in the official [iTerm2 gallery](https://raw.githubusercontent.com/mbadolato/iTerm2-Color-Schemes/master/schemes/Snazzy.itermcolors) works just fine. Not sure if that version is properly synced with the one in this repo, though.
